
  CREATE TABLE "CDS"."IMPORT_SCEN_CFG_TBL" 
   (	
    "SERIAL_NO" NUMBER, 
	"ABS_FILE_NAME" VARCHAR2(500 BYTE), 
	"IMPORT_MODE" VARCHAR2(100 BYTE), 
	"IMPORT_FOLDER" VARCHAR2(100 BYTE)
   );
   
   
  CREATE TABLE "CDS"."DB_OBJ_CFG_TBL" 
   (	
	"SERIAL_NO" NUMBER, 
	"TRG_SCHEMA" VARCHAR2(100 BYTE), 
	"DO_SCRIPT" VARCHAR2(100 BYTE), 
	"UNDO_SCRIPT" VARCHAR2(100 BYTE), 
	"DEPLOY" VARCHAR2(1 BYTE), 
	"ROLL_BACK" VARCHAR2(1 BYTE)
   );
   
   
  CREATE TABLE "CDS"."DB_OBJ_DEPLOY_AUD_EXT" 
   (	
    "FILE_NAME" VARCHAR2(255 BYTE), 
	"OBJECT_NAME" VARCHAR2(500 BYTE), 
	"ERROR_MSG" VARCHAR2(4000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_FILE_LOC"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
        FILE_NAME CHAR(255),
        OBJECT_NAME CHAR(500),
        ERROR_MSG CHAR(4000)
    )
      )
      LOCATION
       ( 'report1.txt'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;
  
  CREATE TABLE CDS.DB_OBJ_DEPLOY_AUD_TBL 
(
FILE_NAME VARCHAR2(255 BYTE),
OBJECT_NAME VARCHAR2(500 BYTE),
ERROR_MSG VARCHAR2(4000 BYTE),
REPORT_DATE DATE
);